"""yarn and pnpm lockfiles. The fixtures are real lockfiles generated by pnpm 7/8/9,
yarn 1.22 and yarn 4 for the same package.json; js-expected-*.txt is the component
set npm resolves for that package.json (the reference)."""

from __future__ import annotations

import json
import shutil
from pathlib import Path

import pytest

from cra_kit.sbom import collect, jslocks, parsers, yaml_lite

from conftest import FIXTURES

EXPECTED_PROD = set((FIXTURES / "js-expected-prod.txt").read_text().split())
EXPECTED_DEV = set((FIXTURES / "js-expected-dev.txt").read_text().split())
DIRECT_PROD = {"@babel/code-frame@7.22.13", "express@4.18.2", "react@18.2.0", "react-dom@18.2.0",
               "string-width@4.2.3"}  # string-width is installed under the alias string-width-cjs
DIRECT_DEV = DIRECT_PROD | {"chai@4.3.10", "debug@4.3.4"}

# Yarn 4 resolved get-intrinsic to 1.3.1 where npm, pnpm and yarn 1 chose 1.3.0; 1.3.1
# brings three new dependencies. The lockfile is real, so the difference is too.
BERRY_DIFF_REMOVE = {"get-intrinsic@1.3.0"}
BERRY_DIFF_ADD = {"get-intrinsic@1.3.1", "async-function@1.0.0", "async-generator-function@1.0.0",
                  "generator-function@2.0.1"}


def identities(result):
    comps = result.deduplicated()
    return {f"{c.name}@{c.version}" for c in comps}, {f"{c.name}@{c.version}" for c in comps if c.direct}


@pytest.mark.parametrize("folder", ["pnpm-v9", "pnpm-v6", "pnpm-v5", "yarn-classic", "npm-alias"])
@pytest.mark.parametrize("include_dev", [False, True])
def test_real_lockfiles_match_reference(folder, include_dev):
    result = collect(FIXTURES / folder, include_dev=include_dev)
    got, direct = identities(result)
    assert got == (EXPECTED_DEV if include_dev else EXPECTED_PROD)
    assert direct == (DIRECT_DEV if include_dev else DIRECT_PROD)
    assert result.warnings == []


@pytest.mark.parametrize("include_dev", [False, True])
def test_yarn_berry(include_dev):
    result = collect(FIXTURES / "yarn-berry", include_dev=include_dev)
    got, direct = identities(result)
    expected = (EXPECTED_DEV if include_dev else EXPECTED_PROD) - BERRY_DIFF_REMOVE | BERRY_DIFF_ADD
    assert got == expected
    assert direct == (DIRECT_DEV if include_dev else DIRECT_PROD)


def test_dev_only_versions_are_excluded():
    got, _ = identities(collect(FIXTURES / "pnpm-v9"))
    assert "debug@2.6.9" in got  # needed by express
    assert "debug@4.3.4" not in got  # dev dependency only
    assert "chai@4.3.10" not in got


def test_npm_alias_is_direct_with_real_name():
    result = parsers.parse_npm_lock(FIXTURES / "npm-alias" / "package-lock.json")
    alias = [c for c in result.components if c.name == "string-width"]
    assert alias and alias[0].direct is True
    assert alias[0].purl == "pkg:npm/string-width@4.2.3"


def test_yarn_classic_without_manifest(tmp_path):
    shutil.copy(FIXTURES / "yarn-classic" / "yarn.lock", tmp_path)
    result = jslocks.parse_yarn_lock(tmp_path / "yarn.lock")
    assert result.components and all(c.direct is None for c in result.components)
    assert {f"{c.name}@{c.version}" for c in result.components} == EXPECTED_DEV
    assert "no package.json" in result.warnings[0]


def test_yarn_berry_workspace_without_manifest(tmp_path):
    shutil.copy(FIXTURES / "yarn-berry" / "yarn.lock", tmp_path)
    result = jslocks.parse_yarn_lock(tmp_path / "yarn.lock")
    got = {f"{c.name}@{c.version}" for c in result.components}
    assert "debug@4.3.4" in got  # dev deps cannot be told apart without package.json
    assert any("development dependencies" in w for w in result.warnings)


def test_yarn_classic_workspaces(tmp_path):
    (tmp_path / "packages" / "web").mkdir(parents=True)
    (tmp_path / "package.json").write_text(json.dumps({"private": True, "workspaces": ["packages/*"]}))
    (tmp_path / "packages" / "web" / "package.json").write_text(json.dumps(
        {"name": "web", "dependencies": {"react": "18.2.0"}, "devDependencies": {"chai": "4.3.10"}}))
    shutil.copy(FIXTURES / "yarn-classic" / "yarn.lock", tmp_path)
    got, direct = identities(collect(tmp_path))
    assert direct == {"react@18.2.0"}
    assert "loose-envify@1.4.0" in got and "chai@4.3.10" not in got


PNPM_WORKSPACE = """\
lockfileVersion: '9.0'

importers:

  .:
    devDependencies:
      left-pad:
        specifier: 1.3.0
        version: 1.3.0

  packages/app:
    dependencies:
      '@scope/util':
        specifier: workspace:*
        version: link:../util
      is-odd:
        specifier: ^3.0.1
        version: 3.0.1
      tool:
        specifier: github:example/tool
        version: https://codeload.github.com/example/tool/tar.gz/abc123

packages:

  is-number@6.0.0:
    resolution: {integrity: sha512-x}

  is-odd@3.0.1:
    resolution: {integrity: sha512-y}
    engines: {node: '>=4'}

  left-pad@1.3.0:
    resolution: {integrity: sha512-z}
    deprecated: use String.prototype.padStart()

  tool@https://codeload.github.com/example/tool/tar.gz/abc123:
    resolution: {tarball: https://codeload.github.com/example/tool/tar.gz/abc123}
    version: 1.0.0

snapshots:

  is-number@6.0.0: {}

  is-odd@3.0.1:
    dependencies:
      is-number: 6.0.0

  left-pad@1.3.0: {}

  tool@https://codeload.github.com/example/tool/tar.gz/abc123: {}
"""


def test_pnpm_workspace_links_and_git(tmp_path):
    (tmp_path / "pnpm-lock.yaml").write_text(PNPM_WORKSPACE)
    result = jslocks.parse_pnpm_lock(tmp_path / "pnpm-lock.yaml")
    got = {(c.name, c.version, c.direct) for c in result.components}
    assert got == {("is-odd", "3.0.1", True), ("is-number", "6.0.0", False)}
    assert any("git, a URL or a local path" in w for w in result.warnings)
    with_dev = {c.name for c in jslocks.parse_pnpm_lock(tmp_path / "pnpm-lock.yaml", include_dev=True).components}
    assert "left-pad" in with_dev


def test_pnpm_multi_document_and_old_versions(tmp_path):
    env = "---\nlockfileVersion: '9.0'\nimporters:\n  .:\n    configDependencies: {}\n---\n"
    (tmp_path / "pnpm-lock.yaml").write_text(env + PNPM_WORKSPACE)
    assert len(jslocks.parse_pnpm_lock(tmp_path / "pnpm-lock.yaml").components) == 2
    (tmp_path / "pnpm-lock.yaml").write_text("lockfileVersion: 4\n")
    assert "too old" in jslocks.parse_pnpm_lock(tmp_path / "pnpm-lock.yaml").warnings[0]


# --- yaml_lite --------------------------------------------------------------


def test_yaml_lite_subset():
    text = """\
# comment
plain: value with spaces
quoted: "a \\"b\\" c"
single: 'it''s'
empty:
flow: {integrity: sha512-abc==, engines: {node: '>=6'}}
list: [x64, arm64]
'key: with colon': 1
nested:
  a:
    - one
    - two: 2
      three: 3
  b: |
    line1
    line2
seq_same_indent:
- p
- q
"""
    assert yaml_lite.load(text) == {
        "plain": "value with spaces",
        "quoted": 'a "b" c',
        "single": "it's",
        "empty": None,
        "flow": {"integrity": "sha512-abc==", "engines": {"node": ">=6"}},
        "list": ["x64", "arm64"],
        "key: with colon": "1",
        "nested": {"a": ["one", {"two": "2", "three": "3"}], "b": "line1\nline2"},
        "seq_same_indent": ["p", "q"],
    }


@pytest.mark.parametrize("bad", ["a: 1\n\tb: 2\n", "a: 1\n   b: 2\n", "a: 'unterminated\n", "just text\n"])
def test_yaml_lite_rejects_unsupported(bad):
    with pytest.raises(ValueError):
        yaml_lite.load(bad)


def test_yaml_lite_matches_pyyaml_on_fixtures():
    yaml = pytest.importorskip("yaml")

    def norm(v):
        if isinstance(v, dict):
            return {str(k): norm(x) for k, x in v.items()}
        if isinstance(v, list):
            return [norm(x) for x in v]
        if isinstance(v, bool):
            return "true" if v else "false"
        return None if v is None else str(v)

    for path in [FIXTURES / "pnpm-v9" / "pnpm-lock.yaml", FIXTURES / "pnpm-v6" / "pnpm-lock.yaml",
                 FIXTURES / "pnpm-v5" / "pnpm-lock.yaml", FIXTURES / "yarn-berry" / "yarn.lock"]:
        text = path.read_text()
        assert yaml_lite.load(text) == norm(yaml.safe_load(text)), path


def test_sbom_of_pnpm_project_validates(tmp_path):
    validation = pytest.importorskip("cyclonedx.validation.json")
    from cyclonedx.schema import SchemaVersion

    from cra_kit.sbom.cyclonedx import build_bom

    bom = build_bom(collect(FIXTURES / "pnpm-v9").deduplicated(), "lock-demo", "1.0.0")
    assert validation.JsonStrictValidator(SchemaVersion.V1_6).validate_str(json.dumps(bom)) is None


def test_fixture_folders_exist():
    for folder in ["pnpm-v9", "pnpm-v6", "pnpm-v5", "yarn-classic", "yarn-berry", "npm-alias"]:
        assert (FIXTURES / folder / "package.json").is_file()
        assert any(p.name in ("pnpm-lock.yaml", "yarn.lock", "package-lock.json") for p in Path(FIXTURES / folder).iterdir())
